projectName: phantom
domain: http://localhost:33333
env: local
port: 33333
httpPort: 33334

database:
  dialect: mysql
  host: 127.0.0.1
  port: 53306 
  dbname: phantom
  username: root
  password: mysqlvotmdnjem

readOnlyDatabase:
  dialect: mysql
  host: 127.0.0.1
  port: 53306 
  dbname: phantom
  username: root
  password: mysqlvotmdnjem

redis:
  host: 127.0.0.1
  port: 56379